---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: https://github.com/python/black.git
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8.git
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--config=./webmonitor/.flake8]
        additional_dependencies:
          - flake8-black>=0.3.6
        language_version: python3
