links = [
    {
        "title": "Reddit - Home Page",
        "description": "Reddit's home page",
        "url": "https://reddit.com",
        "search_regex": "reddit",
        "access_interval": 8,
        "properties": {},
    },
    {
        "title": "Reddit - Python",
        "description": "Reddit's python page",
        "url": "https://reddit.com/r/python",
        "search_regex": "python",
        "access_interval": 8,
        "properties": {},
    },
    {
        "title": "Reddit - FastAPI",
        "description": "Reddit's FastAPI page",
        "url": "https://reddit.com/r/fastapi",
        "search_regex": "fastapi",
        "access_interval": 12,
        "properties": {},
    },
    {
        "title": "IMDb - Home Page",
        "description": "IMDb's home page",
        "url": "https://www.imdb.com",
        "search_regex": "imdb",
        "access_interval": 8,
        "properties": {},
    },
    {
        "title": "IMDb - Top 250",
        "description": "IMDb's top 250 movies page",
        "url": "https://www.imdb.com/chart/top/",
        "search_regex": "imdb",
        "access_interval": 12,
        "properties": {},
    },
    {
        "title": "Kaggle - Covid Search",
        "description": "Kaggle's covid search page",
        "url": "https://www.kaggle.com/search?q=covid",
        "search_regex": "covid",
        "access_interval": 30,
        "properties": {},
    },
    {
        "title": "Kaggle - Titanic Search",
        "description": "Kaggle's titanic search page",
        "url": "https://www.kaggle.com/search?q=titanic",
        "search_regex": "titanic",
        "access_interval": 60,
        "properties": {},
    },
    {
        "title": "Hacker News - Home Page",
        "description": "Hacker News' home page",
        "url": "https://news.ycombinator.com/",
        "search_regex": "hacker news",
        "access_interval": 8,
        "properties": {},
    },
]
